version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
      time: '20:00'
      timezone: 'Asia/Manila'
    commit-message:
      prefix: 'ci'
      prefix-development: 'ci'
      include: 'scope'
