name: 'Setup crane'
description: 'Install and authorize crane'
branding:
  icon: box
  color: green
inputs:
  version:
    description: 'Version of crane to install (tip, latest-release, v0.5.1, etc.)'
    required: true
    default: 'latest-release'
runs:
  using: "composite"
  steps:
  - shell: bash
    env:
      GITHUB_TOKEN: ${{ github.token }}
    run: |
      set -ex

      # Install crane:
      # - if version is "tip", install from tip of main.
      # - if version is "latest-release", look up latest release.
      # - otherwise, install the specified version.
      case ${{ inputs.version }} in
      tip)
        echo "Installing crane using go get"
        go install github.com/google/go-containerregistry/cmd/crane@main
        ;;
      latest-release)
        tag=$(curl -fsSL \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/google/go-containerregistry/releases/latest | jq -r '.tag_name')
        ;;
      *)
        tag="${{ inputs.version }}"
      esac

      os=${{ runner.os }}
      if [[ $os == "macOS" ]]; then
        os="Darwin"
      fi

      arch=$(uname -m)
      if [[ "$arch" =~ (aarch64|arm64) ]] ; then
        arch=arm64
      fi

      out=crane
      if [[ "${os}" == "Windows" ]]; then
        out=crane.exe
      fi

      if [[ ! -z ${tag} ]]; then
        echo "Installing crane @ ${tag} for ${os} on ${arch}"
        tmp=$(mktemp -d)
        cd ${tmp}
        curl -fsL https://github.com/google/go-containerregistry/releases/download/${tag}/go-containerregistry_${os}_${arch}.tar.gz | tar xz ${out}
        chmod +x ${tmp}/${out}
        PATH=${PATH}:${tmp}
        echo "${tmp}" >> $GITHUB_PATH
      fi

      # NB: username doesn't seem to matter.
      echo "${{ github.token }}" | crane auth login ghcr.io --username "dummy" --password-stdin
